### PR TITLE
Add the navigator below the banner with the customized buttons.

### PR DESCRIPTION
**Pull request by seagle0128**
@JesusMtnez @ema2159 , I port the navigator feature from my `Centaur Emacs`. Please review and merge. Thanks!

To show navigator below the banner:
```elisp
(setq dashboard-set-navigator t)
```

To customize the buttons of the navigator like this:
```elisp
;; Format: "icon title help action face"
(setq dashboard-navigator-buttons
      `((,(all-the-icons-octicon "mark-github" :height 1.1 :v-adjust 0.0)
         "Homepage"
         "Browse homepage"
         (lambda (&rest _) (browse-url "homepage")))
        ("★" "Star" "Show stars" (lambda (&rest _) (show-stars)) 'warning)
        ("?" "Help" "?/h" #'show-help nil)))
```

### CODE REVIEW

**Comment by ema2159** [comment]
Hi Mr. Zhang! Yes I'll review it as soon as I can. It seems that the test for Emacs 25 isn't passing, it's probably due to a malformed expression caused by some macro that isn't available for Emacs 25 (i.e. when-let)

**Comment by seagle0128** [comment]
@ema2159 The compatibility issue of Emacs 25 has been addressed.

**Comment by ema2159** [comment]
It works really really nice! however, doesn't it take too much space? Like, isn,'t the space between the navigator and the init info and the logo too big? 
image

**Comment by ema2159** [comment]
Also, it could be pretty nice to add and option to configure the brackets to allow the user to remove them or maybe change their faces, like maybe give the user access to the button-prefix/suffix in the widget create function. Besides from that it's a very very nice addition and it works pretty well.

**Comment by seagle0128** [comment]
>It works really really nice! however, doesn't it take too much space?

@ema2159 I think it's crowed for the page header. I got the screenshots below.

image

image

>Also, it could be pretty nice to add and option to configure the brackets

I will try to add an option and commit soon.

**Comment by JesusMtnez** [comment]
Thank you @seagle0128 for this!! Looks pretty good!!

> @ema2159 I think it's crowed for the page header. I got the screenshots below. I prefer the last one. If all like the first, I will change it.

I prefer the first one :sweat_smile:. If all the widgets are enabled, I would rather see them than having that extra space.

**Comment by seagle0128** [comment]
OK. I understand what you concern. I make it compact.
I am using Macbook Pro 13 plus one 27' 4K monitor :)

**Comment by ema2159** [comment]
That's pretty cool jaja! I think this one es ready to go, it works pretty good and simple! A `dashboard-set-compact` or something like that should do it yes. By the way, just to feel proud, we passed from this:
DeepinScreenshot_select-area_20190604093812

To this in about a month:
DeepinScreenshot_select-area_20190604093553

**Comment by seagle0128** [comment]
Yeah!!! Really happy to implement this in `emacs-dashboard`, although the users of `Centaur` have enjoyed this feature for a few months :-) It brings more customization and better performance indeed. Of course it also makes the configurations simpler and cleaner.

I think it's ready to go now! Please merge, @JesusMtnez .

**Comment by JesusMtnez** [comment]
@seagle0128 Again, really good job here! Thank you!!

Also, thank you @ema2159 also for all your support and contributions too.

I'll proceed to merge this :shipit:

**Pull request merged**
