### PR TITLE
Text startup banner.

### PR DESCRIPTION
**Pull request by jcs090218**
This is the same as #157. I opened another PR because the old PR has been a while and I have deleted the branch.

### CODE REVIEW

**Review by JesusMtnez — APPROVED** [review]
LGTM :shipit:

**Comment by JesusMtnez** [comment]
Why the CI is not running for this branch?

**Comment by jcs090218** [comment]
> Why the CI is not running for this branch?

It's kind of weird. I have checked `circleci`'s website. It does run for each commitment but aren't showing on the commits page. 😕 

Anyway, I realized there are multiple PRs having the same issue. For instance,

#233 - has the CI running
#238 - CI isn't running, including this PR. 

---

Any ideas? 😕 😕

**Comment by jcs090218** [comment]
Merged this PR now. Let me open an issue about the CI isn't running!

**Comment by jcs090218** [comment]
I have toggle the PR build from `circleci` page. I think the CI works in PR for now! 👍

**Pull request merged**
