### PR TITLE
feat: new text banner (old BBC ascii art style)

### PR DESCRIPTION
**Pull request by LionyxML**
Add new option for text banner - old BBC ASCII art alike.

Slightly adapted from: https://github.com/sooriravindra/DotFiles/commit/96bbaf9a770f30c5bf84b6dd4c57519462a9c211#diff-712c8ee1c280142d620dd2539b634c51d3a447e62927a0373e8a9a2bc250a91bR64 by @sooriravindra (https://github.com/sooriravindra)

IMHO this is so cool it would be great to have it bundled within `emacs-dashboard` package as one of the oficial text options.

image

### CODE REVIEW

**Comment by jcs090218** [comment]
It looks cool, but not sure if we should add another banner or not. 🤔

**Comment by DevelopmentCool2449** [comment]
Hello @LionyxML can we use your banner for the new [https://github.com/emacs-dashboard/doom-dashboard](doom-dashboard) package?

**Comment by LionyxML** [comment]
Sure @DevelopmentCool2449! Be my guest!

**Comment by DevelopmentCool2449** [comment]
Banner has been added to [https://github.com/emacs-dashboard/doom-dashboard](doom-dashboard)
Thank you!

**Comment by LionyxML** [comment]
@DevelopmentCool2449  I am sorry to polute this thread a bit further :)

What a SMALL world this is!

I read your post on reddit about the flymake usage with margin. This is something I've been looking for for a long time. I love flycheck and lsp-mode, but I'd love to REALLY try eglot+flymake, like for real, at work. And since I ssh a lot, this would not be nice.

Inspired by your idea and my needs I created a new `flymake` package! like, just finished!

https://github.com/LionyxML/flymake-margin

And just as I was looking for you on reddit to tell the news, surprise surprise, you're the guy asking for the logo! lol

**Comment by DevelopmentCool2449** [comment]
> @DevelopmentCool2449 I am sorry to polute this thread a bit further :)
> 
> What a SMALL world this is!
> 
> I read your post on reddit about the flymake usage with margin. This is something I've been looking for for a long time. I love flycheck and lsp-mode, but I'd love to REALLY try eglot+flymake, like for real, at work. And since I ssh a lot, this would not be nice.
> 
> Inspired by your idea and my needs I created a new `flymake` package! like, just finished!
> 
> https://github.com/LionyxML/flymake-margin

Nice to hear, also i don't know if you know i've sent this feature resquest to [emacs-devel](https://mail.gnu.org/archive/html/emacs-devel/2024-03/msg00354.html)

> Woul'd you mind if I cite you on my README? (Because I did) 😄

Don't worry, i don't have any problem with that

**Comment by LionyxML** [comment]
@DevelopmentCool2449 it looks like the discussion is advanced, I might've build the shortest lived package in the history, lol.

If you'd like to point some configuration feature I've implemented (like a defcustom for setting left/right) to your patch, or even consider develop the package to further to provide the patch from it, feel free to do so.

**Pull request closed without merging**
