### PR TITLE
fix "invalid face property: inherit nil" on navigator icons

### PR DESCRIPTION
**Pull request by mohkale**
this request addresses issue [191](https://github.com/emacs-dashboard/emacs-dashboard/issues/191). It's a small change and logically identical to before, only now there's an extra `nil` check to ensure the text isn't propertized with an invalid face property. 😄.

### CODE REVIEW

**Comment by mohkale** [comment]
I don't think this is ever gonna be merged, so I'll just delete it here.
If anyone else ever ends up facing this issue, you can get around it by
propertizing whatever string you had, that wasn't propertized, with a
non-nil face attribute.

This'll almost certainly be a plain string, which you've tried to use in
place of an icon.

eg. the following works:

```elisp
(setq dashboard-navigator-buttons
      `(((,(propertize "?" 'face '(:inherit default)) ;; needs a face attribute
          "" "emacs FAQ" #'view-emacs-faq font-lock-builtin-face))))
```

**Comment by JesusMtnez** [comment]
Sorry I have not been very active lately. I think it is a valuable pr for the project, I'll review it next week so we can merge it.

**Comment by mohkale** [comment]
@JesusMtnez sorry for the rushed close, I've spent the day cleaning up my account and seeing as theirs a workaround for this issue I decided to close the PR. If you feel it's worth merging that's great, but there's no huge rush; feel free to take your time 😄.

**Review by jcs090218 — COMMENTED** [review]
I have checked, I think this can be merged!

**Pull request closed without merging**
