### PR TITLE
Fix package count when using package.el and straight.el simultaneously

### PR DESCRIPTION
**Pull request by 2bruh4me**
Fix package count when someone is using straight.el and package.el at the same time.

### CODE REVIEW

**Comment by jcs090218** [comment]
@2bruh4me Can you resolve the conflict for us? Thanks! 😄

**Comment by 2bruh4me** [comment]
What is causing the tests to fail?

**Comment by jcs090218** [comment]
Here is the log.

```
dashboard-widgets.el:162:0 (fill-column) line length 100 exceeded
dashboard-widgets.el:164:0 (fill-column) line length 100 exceeded
dashboard-widgets.el FAIL
Makefile:19: recipe for target 'lint' failed
make: *** [lint] Error 1
```

**Comment by 2bruh4me** [comment]
All the problems are resolved now.

**Comment by jcs090218** [comment]
Sorry that we have changed this part of code from `if` to `cond` operation. Do you think you can resolve the conflict from this changes? Sorry for the inconvenience! 😖

**Comment by 2bruh4me** [comment]
@jcs090218 Is this OK?

**Comment by 2bruh4me** [comment]
@jcs090218 Is this good enough?

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
Yes! Thanks for your contribution! ;)

**Pull request merged**
