### PR TITLE
Create a custom variable for dashboard-footer

### PR DESCRIPTION
**Pull request by Luis-Henriquez-Perez**
In general, I think it's a bad idea to calculate `dashboard-footer` or other information that's going to be on the dashbaord in a `defvar` or `defcustom` (any setter) form. This makes these values harder/more annoying to customize. Don't get me wrong you can still customize them, but the calculations will be done before you've even had a chance to decide you want them.

### CODE REVIEW

**Comment by Luis-Henriquez-Perez** [comment]
Is this all set to merge or is there something more to be done from me?

**Comment by Vonfry** [comment]
Would you like to change other variables into `defcustom`, such as `dashboard-navigator-buttons` , `dashboard-startup-banner` and etc.

I fnid them are defined in `defvar`. 

And there a conflicting file in the pr, I suggest you can fix it and the contributors may merge this.

**Comment by ema2159** [comment]
Probably Mr. Martinez missed it or forgot about it, so ask him directly! (@JesusMtnez )

**Comment by JesusMtnez** [comment]
Sorry, I'm been pretty busy during the past few months, lots of personal changes right now. I'll catch up with all the new issues and pull requests after the holidays, sorry for the delay and thank you for your patience.

And, of course, Happy New Year :wink:

**Comment by jcs090218** [comment]
I think this PR should be merged? It looks reasonable.

**Pull request merged**
