### PR TITLE
Disable undo history for dashboard buffer

### LINKED ISSUE #206: No undo history.
I think you would just need to add `(buffer-disable-undo)` to `dashboard-mode`.

### PR DESCRIPTION
**Pull request by jcs090218**
Fixed #206.

### CODE REVIEW

**Comment by jcs090218** [comment]
@JesusMtnez Hi! I know you are quite busy. Just want to ask any progress on maintaining the package? Thanks!

**Comment by JesusMtnez** [comment]
@jcs090218 Sorry, I'm still trying to keep this project up-to-date, but I'm pretty busy. It seems the linter is failing. Could you please update this branch? I sent a fix to `master` a few days ago related to that.

**Comment by jcs090218** [comment]
Okay, I have no idea why the linter isn't working for such a little changes. Do you have any idea?

**Comment by JesusMtnez** [comment]
You need to update against upstream `master`, because you are still missing the changes I made to fix the lint problem. Let me know if you have more trouble.

**Comment by JesusMtnez** [comment]
:tada: There it is :smile:

**Comment by jcs090218** [comment]
😄 Thanks!

**Pull request merged**
