### PR TITLE
Feature/header faces

### PR DESCRIPTION
**Pull request by jkdufair**
Addresses https://github.com/emacs-dashboard/emacs-dashboard/issues/108

### CODE REVIEW

**Comment by JesusMtnez** [comment]
@jkdufair to avoid breaking changes, take a look at: `define-obsolete-face-alias`

That way, you should be able to define an alias to the old name to indicate it is obsolete. You could set this change is included since version `1.2.6` (which will be the release containing this change).

What do you think?

**Comment by jkdufair** [comment]
Oh interesting. Or do you think we are better to just leave it alone?

**Comment by JesusMtnez** [comment]
I like the idea of doing things right, and we have a proper way of doing it

**Comment by jkdufair** [comment]
Great. I'll get it implemented!

**Comment by jkdufair** [comment]
@JesusMtnez Everything look ok?

**Comment by JesusMtnez** [comment]
@jkdufair Everything looks good! Thank you!

**Pull request merged**
