### PR TITLE
Make sure dashboard-resize-on-hook run at the very end of window-size-change-functions

### PR DESCRIPTION
**Pull request by cxa**

### CODE REVIEW

**Comment by jcs090218** [comment]
Thanks for the changes!

I wonder what does this solved? Is there a benefit doing this? Maybe a brief explanation would be great! :)

**Comment by cxa** [comment]
I'm also using `window-size-change-functions` to make my Emacs window shrink and center, to keep `dashboard-resize-on-hook` run after my window resizing customization, this hack is needed. for ref, I attach a screenshot without this hack:
Screen Shot 2022-05-26 at 14 40 18

**Comment by jcs090218** [comment]
Couldn't you refresh dashboard buffer after the set up? Or may be re-order the `window-size-change-functions` to the desire order? 

Hope the information helps! 😅

**Comment by cxa** [comment]
Thanks for your information! As I consult the `add-hook` doc, I found the optional third arg `depth` is very helpful for this situation.

**Review by jcs090218 — APPROVED** [review]
Awesome! I am not quite sure if this would cause any side effect, but by reading docstring it should be an ideal solution.

Let's try this out!

**Pull request merged**
