### PR TITLE
Add support for project.el in the `projects` widget

### PR DESCRIPTION
**Pull request by rudi**
- The library project.el has similar functionality to projectile and is built
  into Emacs >= 27.1.

- To choose the backend, set the variable `dashboard-projects-backend` to
  either `'projectile` or `'project-el`.

### CODE REVIEW

**Comment by jcs090218** [comment]
This looks good to me.

**Comment by rudi** [comment]
> **Edit:** Wait, does `project.el` ever built into Emacs? I am not able to find it's source from my machine.

It is available on gnu elpa and will be in emacs 28.1.  I think it is available in emacs 27 as well, but we need a newer version than the one built-in.

**Comment by jcs090218** [comment]
> It is available on gnu elpa and will be in emacs 28.1. I think it is available in emacs 27 as well, but we need a newer version than the one built-in.

I am on `27.1` and `project.el` isn't here. I guess we will wait until `project.el` is released?

Anyway, thanks for the contribution!

**Comment by rudi** [comment]
> I am on `27.1` and `project.el` isn't here. I guess we will wait until `project.el` is released?

I'm not sure waiting is necessary?  The `project` package is just one `M-x package-install` away, same as `projectile`.

I'll keep the pull request up-to-date - feel free to ping me when conflicts arise since I don't get notified automatically - thanks!

**Comment by jcs090218** [comment]
> I'm not sure waiting is necessary? The project package is just one M-x package-install away, same as projectile. I installed version 0.5.2 from GNU Elpa, works fine on Emacs 27.1.

Ah... Got it! I just noticed this. Sorry for the confusion!

> I'll keep the pull request up-to-date - feel free to ping me when conflicts arise since I don't get notified automatically - thanks!

Thanks! I greatly appreciated! 😄 👍 

---

I will review this within the next few days! And thanks again!

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
Merged! Thanks!

**Pull request merged**
