### PR TITLE
Allow moving the point during dashboard-mode-hook

### PR DESCRIPTION
**Pull request by Dragoncraft89**
If the point is being moved in the dashboard-mode-hook, e.g. moved to the first entry, this has no effect as the point is moved to the beginning of the buffer after the hook.

The point is again moved back to the beginnig during the `emacs-startup-hook`. This one isn't necessary though as the point is not being moved in between.

### CODE REVIEW

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
> The point is again moved back to the beginnig during the emacs-startup-hook. This one isn't necessary though as the point is not being moved in between.

You mean the point is automatically moved to beginning of the buffer in `emacs-startup-hook`? I think we are just ensuring the point start at the beginning of the buffer.

**Comment by Dragoncraft89** [comment]
> You mean the point is automatically moved to beginning of the buffer in emacs-startup-hook?

Exactly

**Review by JesusMtnez — APPROVED** [review]

**Comment by JesusMtnez** [comment]
@Dragoncraft89 Thank you so much for the contribution!!

**Comment by jcs090218** [comment]
I haven't test this patch yet. I will test it with in few days.

**Comment by jcs090218** [comment]
Merged! Thanks!

**Pull request merged**
