### PR TITLE
Vimish bindings

### PR DESCRIPTION
**Pull request by ema2159**
Very simple enhancement, makes j and k move the cursor down and up like in Vim so Evil users feel more familiar. It creates merge conflicts for some absurd reason although it only adds two lines. Also I fixed the screenshot!

### CODE REVIEW

**Comment by JesusMtnez** [comment]
@ema2159 It looks the conflict happens because `screenshot.png` wasn't replaced (as it should be), but only added. Try to recreate the branch from `master` and it should force you to **replace** `screenshot.png`.

**Comment by ema2159** [comment]
I'll try to fix that soon!

**Comment by ema2159** [comment]
@JesusMtnez I'm not able to add the new screenshot correctly, could you help me with that?

**Comment by JesusMtnez** [comment]
@ema2159 Let's not update the screenshot in this PR, just add the vimish bindings. I'll update the `screenshot.png` in another PR. Sounds good?

**Comment by ema2159** [comment]
> @ema2159 Let's not update the screenshot in this PR, just add the vimish bindings. I'll update the `screenshot.png` in another PR. Sounds good?

Ok done!

**Comment by JesusMtnez** [comment]
I'll prepare the `screenshot` tomorrow and I'll merge this PR too. Thank you @ema2159

**Comment by ema2159** [comment]
You're welcome Jesus. It as a pleasure to work with you. If you need something just let me know and I'll be glad to help!

**Pull request merged**
