### PR TITLE
Use dashboard-buffer-name everywhere when invoking buffers

### PR DESCRIPTION
**Pull request by sehnsucht13**
This takes care of #176 and makes it easier to customize for users.

### CODE REVIEW

**Comment by sehnsucht13** [comment]
The lint check does not seem to like the free use of the variable. Looking at the code, there seem to be two options:
1. Ignore the lint check for the free variable. Since dashboard-widgets is required from dashboard.el and the variable is defined inside dashboard.el, there will be no problems loading this at all.
2. Move the offending function which is called `dashboard-append` from `dashboard-widgets.el` to `dashboard`.

Please let me know which is preferable or any other options and I will make sure to implement them. Thanks

**Comment by JesusMtnez** [comment]
@sehnsucht13 Thank you for this change!

Another solution could be:
- Update this branch with latest `master` change.
- Add `(defvar dashboard-buffer-name)` [here](https://github.com/emacs-dashboard/emacs-dashboard/blob/7a71e6ca4c32fdadde0c8624ea4e2e7c11474e7d/dashboard-widgets.el#L23)

**Comment by sehnsucht13** [comment]
Thanks a lot for the quick response and suggestions! I will try to take care of this tommorow!

**Comment by jcs090218** [comment]
Any progress on this? 😕

**Comment by jcs090218** [comment]
Ping @sehnsucht13, I think there is still an error in CI.

**Comment by jcs090218** [comment]
This is completed by eca733a829c5b37ae770a0c881b4c50f7dd646c0 and 02cf7b871c822461ca9063505a3de6a0f79499af.

**Pull request closed without merging**
